### PR TITLE
Rewrite of image meta

### PR DESCRIPTION
**Pull request by evanoberholster**
Rewrite of imagemeta

### CODE REVIEW

**Comment by evanoberholster** [comment]
- [x] Stable ImageTypes API
- [x] Exif parsing for jpg, heif, cr2, tiff, and dng
- [x] Exif parsing for CR3
- [x] Camera Make and Model lookup tables
- [x] Stable Imagemeta API
- [x] Canon Makernote initial support
- [x] Nikon Makernote initial support
- [ ] Exif parsing for AVIF (ISOBMFF format)
- [ ] Exif parsing for CRW (ciff format)
- [ ] Preview image extraction
- [ ] Test coverage >50%

**Comment by evanoberholster** [comment]
Issues addressed:
- [x] Exif timezone support Offsets  #26 
- [x] Parse function in imagemeta #47 
- [x] Initial Exif parsing of PNG files #41 implemented by @abrander  
- [x] Add initial AVIF support, will require further testing #44

**Comment by mholt** [comment]
@evanoberholster I finally had a chance to clone this down and try it out. So far, it works! The `Decode()` function works nicely and returns timestamp and coordinate data with values as expected. I have yet to try other fields.

Is there a way to get all the extracted EXIF fields? Like a map I can iterate over?

It's OK if these fields don't have any special interpreation: just a key-value store of whatever fields were discovered. This would be easier for me to work with than a huge struct with hard-coded fields. (I think some struct fields are OK, especially if they are common or need interpretation to be useful -- but I'd still like a map of everything that was parsed anyway.)

Sorry if I have a lot of requests :upside_down_face: I think we're getting close to something that works for my use case! :tada:

**Comment by evanoberholster** [comment]
Thanks for the suggestion, as this is an enhancement that will need further work. Would prefer that it were merged from a new PR request. There for I have opened issue #49 

The goal is to merge ```develop``` as soon as possible as it is a rewrite.

**Comment by mholt** [comment]
Makes sense - thanks!

**Comment by mholt** [comment]
Congrats on the rewrite :smiley:

**Pull request merged**
