### PR TITLE
Fix rating not being parsed

### PR DESCRIPTION
**Pull request by Maddosaurus**
Hey Evan,

first of all: Thanks for this nice project!

While playing around with it for my use case, I discovered that the Rating (at least in XMP files) is not parsed correctly.
It will always stay 0, due to the source var in XMP being a uint8, so the wrong parsing function is used.
I've changed the call and can verify that the updated parsing yields the correct results for XMP files generated by Lightroom CC.

Side note: I tried to get the tests that read `1.xmp` and its JSON to fail, but was unable to. That might be on my end, so I'd be interested in how the file-based tests work.

If you'd like, I can also provide the XMP to you, just let me know 😄

### CODE REVIEW

**Comment by Maddosaurus** [comment]
@evanoberholster Happy New Year! Do you happen to have some minutes to take a look at this PR?

**Review by mholt — APPROVED** [review]

**Comment by Maddosaurus** [comment]
@mholt thanks for approving, but it looks like I cannot merge the PR on my own. Would you mind doing the honors? Thanks :heart:

**Comment by mholt** [comment]
I don't have commit privileges, I just wanted to support your change as I think this project is really useful.

**Review by evanoberholster — APPROVED** [review]
Thanks for making this change it is appropriate and appreciated. Will merge.

**Pull request merged**
